/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyPendingRouteImport } from './routes/verify-pending'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PacksRouteImport } from './routes/packs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KitsRouteImport } from './routes/kits'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogSlugRouteImport } from './routes/catalog.$slug'
import { Route as ApiPaymentCallbackRouteImport } from './routes/api.payment-callback'
import { Route as ApiFedapayWebhookRouteImport } from './routes/api.fedapay-webhook'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPaymentPaymentIdRouteImport } from './routes/_authenticated/payment.$paymentId'
import { Route as AuthenticatedAdminRequests_pendingRouteImport } from './routes/_authenticated/admin.requests_pending'
import { Route as AuthenticatedAdminRequestsRouteImport } from './routes/_authenticated/admin.requests'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin.messages'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin.clients'
import { Route as AuthenticatedAdminCatalogRouteImport } from './routes/_authenticated/admin.catalog'
import { Route as AuthenticatedAdminClientsClientIdRouteImport } from './routes/_authenticated/admin.clients.$clientId'
import { Route as AuthenticatedAdminCatalogNewRouteImport } from './routes/_authenticated/admin.catalog.new'
import { Route as AuthenticatedAdminCatalogIdRouteImport } from './routes/_authenticated/admin.catalog.$id'

const VerifyPendingRoute = VerifyPendingRouteImport.update({
  id: '/verify-pending',
  path: '/verify-pending',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksRoute = PacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KitsRoute = KitsRouteImport.update({
  id: '/kits',
  path: '/kits',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogSlugRoute = CatalogSlugRouteImport.update({
  id: '/catalog/$slug',
  path: '/catalog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentCallbackRoute = ApiPaymentCallbackRouteImport.update({
  id: '/api/payment-callback',
  path: '/api/payment-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFedapayWebhookRoute = ApiFedapayWebhookRouteImport.update({
  id: '/api/fedapay-webhook',
  path: '/api/fedapay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaymentPaymentIdRoute =
  AuthenticatedPaymentPaymentIdRouteImport.update({
    id: '/payment/$paymentId',
    path: '/payment/$paymentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRequests_pendingRoute =
  AuthenticatedAdminRequests_pendingRouteImport.update({
    id: '/requests_pending',
    path: '/requests_pending',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRequestsRoute =
  AuthenticatedAdminRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCatalogRoute =
  AuthenticatedAdminCatalogRouteImport.update({
    id: '/catalog',
    path: '/catalog',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientsClientIdRoute =
  AuthenticatedAdminClientsClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => AuthenticatedAdminClientsRoute,
  } as any)
const AuthenticatedAdminCatalogNewRoute =
  AuthenticatedAdminCatalogNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminCatalogRoute,
  } as any)
const AuthenticatedAdminCatalogIdRoute =
  AuthenticatedAdminCatalogIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminCatalogRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kits': typeof KitsRoute
  '/login': typeof LoginRoute
  '/packs': typeof PacksRoute
  '/process': typeof ProcessRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-pending': typeof VerifyPendingRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/fedapay-webhook': typeof ApiFedapayWebhookRoute
  '/api/payment-callback': typeof ApiPaymentCallbackRoute
  '/catalog/$slug': typeof CatalogSlugRoute
  '/admin/catalog': typeof AuthenticatedAdminCatalogRouteWithChildren
  '/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/requests_pending': typeof AuthenticatedAdminRequests_pendingRoute
  '/payment/$paymentId': typeof AuthenticatedPaymentPaymentIdRoute
  '/admin/catalog/$id': typeof AuthenticatedAdminCatalogIdRoute
  '/admin/catalog/new': typeof AuthenticatedAdminCatalogNewRoute
  '/admin/clients/$clientId': typeof AuthenticatedAdminClientsClientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kits': typeof KitsRoute
  '/login': typeof LoginRoute
  '/packs': typeof PacksRoute
  '/process': typeof ProcessRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-pending': typeof VerifyPendingRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/fedapay-webhook': typeof ApiFedapayWebhookRoute
  '/api/payment-callback': typeof ApiPaymentCallbackRoute
  '/catalog/$slug': typeof CatalogSlugRoute
  '/admin/catalog': typeof AuthenticatedAdminCatalogRouteWithChildren
  '/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/requests_pending': typeof AuthenticatedAdminRequests_pendingRoute
  '/payment/$paymentId': typeof AuthenticatedPaymentPaymentIdRoute
  '/admin/catalog/$id': typeof AuthenticatedAdminCatalogIdRoute
  '/admin/catalog/new': typeof AuthenticatedAdminCatalogNewRoute
  '/admin/clients/$clientId': typeof AuthenticatedAdminClientsClientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kits': typeof KitsRoute
  '/login': typeof LoginRoute
  '/packs': typeof PacksRoute
  '/process': typeof ProcessRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-pending': typeof VerifyPendingRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/fedapay-webhook': typeof ApiFedapayWebhookRoute
  '/api/payment-callback': typeof ApiPaymentCallbackRoute
  '/catalog/$slug': typeof CatalogSlugRoute
  '/_authenticated/admin/catalog': typeof AuthenticatedAdminCatalogRouteWithChildren
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/_authenticated/admin/requests_pending': typeof AuthenticatedAdminRequests_pendingRoute
  '/_authenticated/payment/$paymentId': typeof AuthenticatedPaymentPaymentIdRoute
  '/_authenticated/admin/catalog/$id': typeof AuthenticatedAdminCatalogIdRoute
  '/_authenticated/admin/catalog/new': typeof AuthenticatedAdminCatalogNewRoute
  '/_authenticated/admin/clients/$clientId': typeof AuthenticatedAdminClientsClientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/forgot-password'
    | '/kits'
    | '/login'
    | '/packs'
    | '/process'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/verify-pending'
    | '/admin'
    | '/dashboard'
    | '/api/fedapay-webhook'
    | '/api/payment-callback'
    | '/catalog/$slug'
    | '/admin/catalog'
    | '/admin/clients'
    | '/admin/messages'
    | '/admin/requests'
    | '/admin/requests_pending'
    | '/payment/$paymentId'
    | '/admin/catalog/$id'
    | '/admin/catalog/new'
    | '/admin/clients/$clientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/forgot-password'
    | '/kits'
    | '/login'
    | '/packs'
    | '/process'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/verify-pending'
    | '/admin'
    | '/dashboard'
    | '/api/fedapay-webhook'
    | '/api/payment-callback'
    | '/catalog/$slug'
    | '/admin/catalog'
    | '/admin/clients'
    | '/admin/messages'
    | '/admin/requests'
    | '/admin/requests_pending'
    | '/payment/$paymentId'
    | '/admin/catalog/$id'
    | '/admin/catalog/new'
    | '/admin/clients/$clientId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/contact'
    | '/forgot-password'
    | '/kits'
    | '/login'
    | '/packs'
    | '/process'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/verify-pending'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/api/fedapay-webhook'
    | '/api/payment-callback'
    | '/catalog/$slug'
    | '/_authenticated/admin/catalog'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/requests'
    | '/_authenticated/admin/requests_pending'
    | '/_authenticated/payment/$paymentId'
    | '/_authenticated/admin/catalog/$id'
    | '/_authenticated/admin/catalog/new'
    | '/_authenticated/admin/clients/$clientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  KitsRoute: typeof KitsRoute
  LoginRoute: typeof LoginRoute
  PacksRoute: typeof PacksRoute
  ProcessRoute: typeof ProcessRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  VerifyPendingRoute: typeof VerifyPendingRoute
  ApiFedapayWebhookRoute: typeof ApiFedapayWebhookRoute
  ApiPaymentCallbackRoute: typeof ApiPaymentCallbackRoute
  CatalogSlugRoute: typeof CatalogSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-pending': {
      id: '/verify-pending'
      path: '/verify-pending'
      fullPath: '/verify-pending'
      preLoaderRoute: typeof VerifyPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs': {
      id: '/packs'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof PacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kits': {
      id: '/kits'
      path: '/kits'
      fullPath: '/kits'
      preLoaderRoute: typeof KitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$slug': {
      id: '/catalog/$slug'
      path: '/catalog/$slug'
      fullPath: '/catalog/$slug'
      preLoaderRoute: typeof CatalogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment-callback': {
      id: '/api/payment-callback'
      path: '/api/payment-callback'
      fullPath: '/api/payment-callback'
      preLoaderRoute: typeof ApiPaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fedapay-webhook': {
      id: '/api/fedapay-webhook'
      path: '/api/fedapay-webhook'
      fullPath: '/api/fedapay-webhook'
      preLoaderRoute: typeof ApiFedapayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payment/$paymentId': {
      id: '/_authenticated/payment/$paymentId'
      path: '/payment/$paymentId'
      fullPath: '/payment/$paymentId'
      preLoaderRoute: typeof AuthenticatedPaymentPaymentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/requests_pending': {
      id: '/_authenticated/admin/requests_pending'
      path: '/requests_pending'
      fullPath: '/admin/requests_pending'
      preLoaderRoute: typeof AuthenticatedAdminRequests_pendingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/requests': {
      id: '/_authenticated/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AuthenticatedAdminRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/catalog': {
      id: '/_authenticated/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AuthenticatedAdminCatalogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clients/$clientId': {
      id: '/_authenticated/admin/clients/$clientId'
      path: '/$clientId'
      fullPath: '/admin/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedAdminClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedAdminClientsRoute
    }
    '/_authenticated/admin/catalog/new': {
      id: '/_authenticated/admin/catalog/new'
      path: '/new'
      fullPath: '/admin/catalog/new'
      preLoaderRoute: typeof AuthenticatedAdminCatalogNewRouteImport
      parentRoute: typeof AuthenticatedAdminCatalogRoute
    }
    '/_authenticated/admin/catalog/$id': {
      id: '/_authenticated/admin/catalog/$id'
      path: '/$id'
      fullPath: '/admin/catalog/$id'
      preLoaderRoute: typeof AuthenticatedAdminCatalogIdRouteImport
      parentRoute: typeof AuthenticatedAdminCatalogRoute
    }
  }
}

interface AuthenticatedAdminCatalogRouteChildren {
  AuthenticatedAdminCatalogIdRoute: typeof AuthenticatedAdminCatalogIdRoute
  AuthenticatedAdminCatalogNewRoute: typeof AuthenticatedAdminCatalogNewRoute
}

const AuthenticatedAdminCatalogRouteChildren: AuthenticatedAdminCatalogRouteChildren =
  {
    AuthenticatedAdminCatalogIdRoute: AuthenticatedAdminCatalogIdRoute,
    AuthenticatedAdminCatalogNewRoute: AuthenticatedAdminCatalogNewRoute,
  }

const AuthenticatedAdminCatalogRouteWithChildren =
  AuthenticatedAdminCatalogRoute._addFileChildren(
    AuthenticatedAdminCatalogRouteChildren,
  )

interface AuthenticatedAdminClientsRouteChildren {
  AuthenticatedAdminClientsClientIdRoute: typeof AuthenticatedAdminClientsClientIdRoute
}

const AuthenticatedAdminClientsRouteChildren: AuthenticatedAdminClientsRouteChildren =
  {
    AuthenticatedAdminClientsClientIdRoute:
      AuthenticatedAdminClientsClientIdRoute,
  }

const AuthenticatedAdminClientsRouteWithChildren =
  AuthenticatedAdminClientsRoute._addFileChildren(
    AuthenticatedAdminClientsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCatalogRoute: typeof AuthenticatedAdminCatalogRouteWithChildren
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRouteWithChildren
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminRequestsRoute: typeof AuthenticatedAdminRequestsRoute
  AuthenticatedAdminRequests_pendingRoute: typeof AuthenticatedAdminRequests_pendingRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCatalogRoute: AuthenticatedAdminCatalogRouteWithChildren,
  AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRouteWithChildren,
  AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
  AuthenticatedAdminRequestsRoute: AuthenticatedAdminRequestsRoute,
  AuthenticatedAdminRequests_pendingRoute:
    AuthenticatedAdminRequests_pendingRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPaymentPaymentIdRoute: typeof AuthenticatedPaymentPaymentIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPaymentPaymentIdRoute: AuthenticatedPaymentPaymentIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  KitsRoute: KitsRoute,
  LoginRoute: LoginRoute,
  PacksRoute: PacksRoute,
  ProcessRoute: ProcessRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  VerifyPendingRoute: VerifyPendingRoute,
  ApiFedapayWebhookRoute: ApiFedapayWebhookRoute,
  ApiPaymentCallbackRoute: ApiPaymentCallbackRoute,
  CatalogSlugRoute: CatalogSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
